---

- name: set up standard packages
  apt:
    state: present
    pkg:
      - htop
      - emacs-nox
      - docker
      - docker-compose
      - hugo
      - lsof
      - mosh
      - tmux
      - zsh
      - kakoune
      - kitty-terminfo
      - weechat
      - yaml-mode
      - sqlite3
      - libpam-systemd
      - ftp
      - netcat
      - tig
